#!/bin/bash
# direnv 快速配置命令
# 请按顺序执行以下命令

echo "========================================================"
echo "     direnv 配置命令"
echo "========================================================"
echo ""
echo "请按顺序执行以下命令："
echo ""
echo "1. 安装 direnv:"
echo "   brew install direnv"
echo ""
echo "2. 配置 zsh (添加到 ~/.zshrc):"
echo "   echo '' >> ~/.zshrc"
echo "   echo '# direnv 配置 - 自动激活虚拟环境' >> ~/.zshrc"
echo "   echo 'eval \"\$(direnv hook zsh)\"' >> ~/.zshrc"
echo ""
echo "3. 重新加载配置:"
echo "   source ~/.zshrc"
echo ""
echo "4. 允许项目的 .envrc:"
echo "   cd /Users/jameswilson/SPECT"
echo "   direnv allow"
echo ""
echo "5. 测试 (进入项目目录):"
echo "   cd /Users/jameswilson/SPECT"
echo "   # 应该看到: direnv: loading .envrc"
echo "   # 提示符前应该有: (.venv)"
echo ""
echo "========================================================"
